#! /usr/bin/env python3

import os, sys

_sites:set = {}
_scan_dir:str = ''

def interactive() -> None:

	sites:set[str] = {}

	while True:
		userin = input('>> ').split()

		if len(userin) == 0:
			pass
		elif userin[0] == 'quit':
			break
		elif userin[0] == 'add':
			if len(userin) <= 2:
				print("Invalid Usecase!\tUSE add [site/lib] `name`")
			else:
				if userin[1] == 'lib':
					if userin[2] in os.listdir():
						for site in open(userin[2], 'r').read().split('\n'):
							sites.add(site)
					else:
						print("Library not recognized!")
				else:
					pass

def genscan(*args) -> None:
	"""Used to make scan from passed in arguemnts"""
	sites:set = set([ arg for arg in args if arg in _sites ])
	if '-u' in args:
		for scan in args[args.index('-u'):]
			try:
				for site in open(_scan_dir+'/'+scan, 'r').read().split('\n'):
					
	


def display_help() -> None:
	"""Used to display help message to terminal"""
	print('makescan - help\n\nUsage:\n\tmakescan site1 site2 ... siteN -u scan1 scan2 ... scanN\n\tmakesite -I')

if __name_ == '__main__':
	if '-I' in sys.argv:
		interactive()
	elif '-n' in sys.argv and ('-i' in sys.argv or '-u' in sys.argv):
		genscan(*sys.argv[1:])
	else:
		display_help()
	sys.exit()
