#! /usr/bin/env python3.10

import os, sys
import json

SITE_INDEX:dict = json.load(open(os.environ["HOME"]+'/.pyhund/lib/manifest.json', 'r'))

def display_site(name):
	try:
		_sd = SITE_INDEX[name.strip()]
		print(f"\033[38;2;0;0;0m\033[48;2;202;254;1m {name} \033[0m")
		[print(f"\t\033[38;2;0;0;0m\033[48;2;202;254;1m {k} \033[0m \033[38;2;202;254;1m{_sd[k]}\033[0m") for k in _sd]
	except KeyError:
		print(f"\033[1;91m{name} does not exist!\033[0m")

def interactive():

	while True:
		_cmd = input('\033[38;2;0;0;0m\033[48;2;202;254;1m << \033[0m ')
		if _cmd == 'quit':
			break

		if _cmd == 'help':
			print('\033[38;2;0;0;0m\033[48;2;202;254;1m? - ? args - shows if sites exist\033[0m\n\033[38;2;0;0;0m\033[48;2;202;254;1mshow - show args - displays site for each site in args\033[0m')

		match _cmd.split()[0]:
			case '?':
				[ print(f"\t\033[38;2;0;0;0m\033[48;2;202;254;1m{s}\033[0m\033[38;2;202;254;1m Exists in Sites\033[0m") for s in _cmd.split()[1:] if s in SITE_INDEX ]
			case 'show':
				[ display_site(s) for s in _cmd.split()[1:] ]

def main():
	if '-i' in sys.argv:
		interactive()
	else:
		[display_site(_s) for _s in sys.argv[1:] if not _s.startswith("-")]

if __name__ == '__main__':
	main()
